name: maids_todo_app_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  go_router: ^14.1.1
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  intl: ^0.19.0
  get_it: ^7.7.0
  injectable:
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio_cache_interceptor: ^3.5.0
  internet_connection_checker: ^1.0.0+1
  flutter_screenutil:
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  flutter_animate: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.10
  # Dependency injection code generator
  injectable_generator: ^2.6.1
  # Freezed package code generator
  freezed: ^2.5.2
  # Used in freezed package
  json_serializable: ^6.8.0
  # Used to change app icon
  flutter_launcher_icons: ^0.13.1
  # Used to change the native splash screen
  flutter_native_splash: ^2.4.0
  # Change App Package Name with single command.
  change_app_package_name: ^1.1.0
  sqflite: ^2.3.3+1
flutter:
  uses-material-design: true
  assets:
    - assets/images/png/

